# Generated by Django 3.1.7 on 2021-03-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormCadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('data_criacao', models.DateTimeField()),
            ],
        ),
    ]
