# Generated by Django 3.1.7 on 2021-03-17 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormCadastro',
            new_name='Usuario',
        ),
    ]
