# Generated by Django 3.1.7 on 2021-03-31 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20210325_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Segmento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.segmento'),
        ),
    ]
